// <auto-generated />
namespace PAWA.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FolderTableForeignKeyFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FolderTableForeignKeyFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201310141442145_FolderTableForeignKeyFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
