<%@ Page Title="Title" Language="C#" Inherits="System.Web.Mvc.ViewPage<AwesomeMvcDemo.ViewModels.LookupCrudInput>" MasterPageFile="~/Views/Shared/Site.Master" %>

<asp:Content runat="server" ID="Title" ContentPlaceHolderID="TitleContent">
ASP.net MVC Awesome Lookup with CRUD functionality inside it's Popup
</asp:Content>
<asp:Content runat="server" ID="Main" ContentPlaceHolderID="MainContent">    
    <% using (Html.BeginForm())
       {%>
        <h3>Lookup with CRUD functionality in it's Popup</h3>
        <div class="efield">
            <div class="elabel">
                Dinner:</div>
            <div class="einput">
                <%:Html.Awe().LookupFor(o => o.Dinner).CustomSearch(true).TableLayout(true).HighlightChange(true).Fullscreen(true) %>
            </div>
            <%:Html.ValidationMessageFor(o => o.Dinner) %>
        </div>
        <input type="submit" value="Submit" class="awe-btn" />
    <%}%>
    <%:Html.Awe().Form().FormClass("confirm").Confirm(true).Success("del") %>
    <script type="text/javascript">
        function edit(o) {
            $('#dinner' + o.Id).fadeOut(300, function () { $(this).after(o.Content).remove(); });
        }
        function del(o) {
            $('#dinner' + o.Id).fadeOut(300, function () { $(this).remove(); });
        }
        //Dinner-awepw is the id of the popup generated by the lookup Dinner
        function create(o) {
            $('#Dinner-awepw').find('tbody').prepend(o.Content);
        }
    </script>
</asp:Content>
